# Generated by Django 5.1.5 on 2025-01-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'verbose_name': 'Hizmet Özelliği', 'verbose_name_plural': 'Hizmet Özellikleri'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Teknoloji', 'verbose_name_plural': 'Teknolojiler'},
        ),
    ]
